param(
    [string]$Compiler = "",
    [string]$Python = "",
    [string]$Spec = "MotuNet.spec",
    [string]$StagingRoot = "staging",
    [string]$OutputDir = "deliverables",
    [string]$Repository = "",
    [string[]]$CompilerArgs = @()
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $projectRoot

function Resolve-BuildExecutable([string]$Requested, [string[]]$Candidates, [string]$Label) {
    $choices = if ($Requested) { @($Requested) } else { $Candidates }
    foreach ($candidate in $choices) {
        if (-not $candidate) { continue }
        if (Test-Path -LiteralPath $candidate -PathType Leaf) {
            return (Resolve-Path -LiteralPath $candidate).Path
        }
        $command = Get-Command -Name $candidate -CommandType Application -ErrorAction SilentlyContinue
        if ($command) { return $command.Source }
    }
    throw "未找到 $Label；请通过对应参数指定可执行文件。"
}

$Python = Resolve-BuildExecutable $Python @(".venv\Scripts\python.exe", "python.exe", "python") "Python"
$Compiler = Resolve-BuildExecutable $Compiler @(
    "$env:LOCALAPPDATA\MutuNetBuildTools\InnoSetup\ISCC.exe",
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
    "ISCC.exe"
) "Inno Setup 编译器"
if (-not (Test-Path -LiteralPath $Spec -PathType Leaf)) { throw "未找到 PyInstaller spec: $Spec" }

$metadataText = & $Python -c "import json; from netlab import __version__; from netlab.update_source import UPDATE_REPOSITORY; print(json.dumps({'version': __version__, 'repository': UPDATE_REPOSITORY}))"
if ($LASTEXITCODE -ne 0) { throw "无法读取应用版本或更新仓库配置" }
$metadata = ($metadataText -join "`n") | ConvertFrom-Json
$version = $metadata.version
if (-not $Repository) { $Repository = $metadata.repository }
if (-not $Repository) { throw "尚未配置更新仓库：请先填写 netlab/update_source.py 中的 UPDATE_REPOSITORY。" }
if ($Repository -cne $metadata.repository) {
    throw "发布仓库与 netlab/update_source.py 中的 UPDATE_REPOSITORY 不一致。"
}

# Validate the version, fixed repository and release notes before producing binaries.
& $Python tools/make_update_manifest.py --repository $Repository --validate-only
if ($LASTEXITCODE -ne 0) { throw "发布配置校验失败" }

$distRoot = [IO.Path]::GetFullPath((Join-Path $projectRoot $StagingRoot))
$stage = Join-Path $distRoot "MotuNet"
$workRoot = Join-Path $projectRoot ".build\motu"
$releaseOutput = [IO.Path]::GetFullPath((Join-Path $projectRoot $OutputDir))
$null = New-Item -ItemType Directory -Force -Path $distRoot,$workRoot,$releaseOutput
$versionRecord = "# Generated by tools/build_release.ps1 from netlab.__version__; do not edit.`n$version`n"
[IO.File]::WriteAllText((Join-Path $projectRoot "packaging\version_info.txt"), $versionRecord, [Text.UTF8Encoding]::new($false))

& $Python -m PyInstaller --clean --noconfirm --distpath $distRoot --workpath $workRoot $Spec
if ($LASTEXITCODE -ne 0) { throw "PyInstaller 构建失败，退出码 $LASTEXITCODE" }

if (-not (Test-Path -LiteralPath (Join-Path $stage "MotuNet.exe") -PathType Leaf)) {
    throw "构建后未找到 $stage\MotuNet.exe；请确认 spec 的 EXE 名称为 MotuNet。"
}

$iss = Join-Path $projectRoot "packaging\MotuNet.iss"
$innoArguments = @($CompilerArgs) + @(
    "/DAppVersion=$version", "/DPayloadDir=$stage", "/DReleaseOutputDir=$releaseOutput", $iss
)
& $Compiler @innoArguments
if ($LASTEXITCODE -ne 0) { throw "Inno Setup 构建失败，退出码 $LASTEXITCODE" }

$artifact = Join-Path $releaseOutput "MotuNet-$version-Setup-x64.exe"
if (-not (Test-Path -LiteralPath $artifact -PathType Leaf)) { throw "未找到安装包输出: $artifact" }
& $Python tools/make_update_manifest.py --repository $Repository --installer $artifact --output-dir $releaseOutput
if ($LASTEXITCODE -ne 0) { throw "更新清单生成失败" }
Write-Host "安装包及更新清单已生成：$releaseOutput"
